### ISSUE TITLE
Is it possible to use it for clonezilla ?

### ISSUE THREAD

**Issue by braxtoon-hash** [benkehoe/aws-sso-util#111]
Hello i need to connect to an AWS S3 bucket when cloning/restoring but clonezilla doesn't handle SSO, so is it possible to use your project for clonezilla ?

Ty and have a good day !

**Comment by benkehoe** [comment]
A quick google didn't turn up any information for me on how clonezilla integrates with AWS. Can you point me to some documentation on that? I can take a look and see if I can figure out how it's getting credentials.

**Comment by iainelder** [comment]
I think you need to copy the temporary credentials from SSO into either the default shared credentials file or the standard environment variables.

The default shared credentials file is at `${HOME}/.aws/credentials`. My guess is that you will have to use the `[default]` section of this file for CloneZilla because I don't see how you would set a profile name.

The standard environment variables are `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY`, and `AWS_SESSION_TOKEN`.

aws-sso-util, as far as I know, never changes those because instead it acts as a process credential provider (sets `credential_process` in the config file).

---

CloneZilla supports S3 as an image directory. It depends on [s3fs-fuse](https://github.com/s3fs-fuse/s3fs-fuse).

CloneZilla mentions S3 in the [Save disk image](https://clonezilla.org/show-live-doc-content.php?topic=clonezilla-live/doc/01_Save_disk_image) documentation.

> There are other options, e.g. sshfs, samba, nfs or [webdav](http://en.wikipedia.org/wiki/WebDAV), [AWS S3](https://en.wikipedia.org/wiki/Amazon_S3) or [Openstack Swift](https://en.wikipedia.org/wiki/OpenStack), you can use when network is available. This is very useful when 2nd local disk is not available.

![image](https://github.com/benkehoe/aws-sso-util/assets/5024311/58790d97-a294-46e8-8f08-5a8cf305262e)

See the [do_mount_s3_server function](https://github.com/stevenshiau/clonezilla/blob/11712ef00c71214f0a434c9332d0c581847c008a/sbin/ocs-prep-repo#L978-L1007) and [changelog](https://clonezilla.org/downloads/stable/changelog.php) entries 2.4.1-11 and 2.4.1-2 for more clues.

s3fs-fuse, according to [s3fs_cred.cpp](https://github.com/s3fs-fuse/s3fs-fuse/blob/a83f4a48d0286062fc6837e913a523c3286974fd/src/s3fs_cred.cpp#L883-L954), can read temporary credentials from `${HOME}/.aws/credentials` and from the environment variables `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY`, and `AWS_SESSION_TOKEN`.

**Comment by benkehoe** [comment]
Thanks @iainelder. While [you should never put temporary credentials in environment variables or the credentials file](https://medium.com/@ben11kehoe/never-put-aws-temporary-credentials-in-env-vars-or-credentials-files-theres-a-better-way-25ec45b4d73e) if you can help it, when you're using tools that force you to, there's [aws-export-credentials](https://github.com/benkehoe/aws-export-credentials) for that.

**Comment by iainelder** [comment]
Thanks @benkehoe! I learned from these quotes from your linked article:

> Update 2023–05–24: The AWS CLI v2 now includes the command [aws configure export-credentials](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/configure/export-credentials.html), which includes some of the functionality covered by aws-export-credentials (JSON and environment variables, including for Windows and PowerShell).

I'm glad the stock CLI now has a solution for for copying the credentials. I had been using [aws2-wrap](https://github.com/linaro-its/aws2-wrap) to achieve the same thing. (I'll be even gladder when everything just supports Identity Center!)

> Please don’t build tools that way yourself, but if you’re forced to use one, you have no choice but to provide explicit credentials (but open a feature request asking for proper support).

The s3fs-fuse developers are working on [adding support for SSO credentials](https://github.com/s3fs-fuse/s3fs-fuse/pull/2165). They are also working on [replacing the custom authentication code with the standard AWS C++ SDK](https://github.com/s3fs-fuse/s3fs-fuse/issues/1068).

@Titouanwallahi , you could share a :+1: on those issues to show your interest.

**Comment by Titouanwallahi** [comment]
Thank you guys !

**Comment by darioackermann** [comment]
SSO PR opener at s3fs-fuse here. Given that the discussion on https://github.com/s3fs-fuse/s3fs-fuse/pull/2165 is stuck since June, I do not believe it to be merged anytime soon. Sorry for the bummer.
