### ISSUE TITLE
Unable to locate credentials

### ISSUE THREAD

**Issue by ryan-mars** [benkehoe/aws-sso-util#17]
**Expected behavior:**

Don't get an error

**Actual behavior:** 

`botocore.exceptions.NoCredentialsError: Unable to locate credentials`

**Actions:**

`aws-sso-util configure`

`aws-sso-util login`

Everything works fine at this point, including CDK. 

`aws-sso-util lookup user soandso@suchandsuch.com` 

See a stack trace ending with 
`botocore.exceptions.NoCredentialsError: Unable to locate credentials`

`~./aws/credentials` is an empty file.

**Comment by benkehoe** [comment]
`aws-sso-util lookup` and `aws-sso-util assignments` are both admin calls; they require existing AWS credentials in your Organizations management account that have permissions to access [`identitystore:ListUsers`](https://docs.aws.amazon.com/singlesignon/latest/IdentityStoreAPIReference/API_ListUsers.html) and such for `lookup` and a variety of permissions for `assignments` like [`sso-admin:ListAccountAssignments`](https://docs.aws.amazon.com/singlesignon/latest/APIReference/API_ListAccountAssignments.html).
For these APIs, you could have logged in using AWS SSO, but you could also be a traditional SAML-federated IAM role, an IAM user, or even (god forbid) credentials for the account root.

By contrast, `aws-sso-util login`, `aws-sso-util configure`, and `aws-sso-util roles` operate on the [SSO OIDC](https://docs.aws.amazon.com/singlesignon/latest/OIDCAPIReference/Welcome.html) and [SSO Portal](https://docs.aws.amazon.com/singlesignon/latest/PortalAPIReference/index.html) APIs, which deal with the authentication process and the access a given user's token has. It's all before the resolution into a particular account and role.

Put it this way: what account and role were you expecting `aws-sso-util lookup` was going to use?

How could this be made more clear? Better documentation? Maybe grouping these admin calls together, something like `aws-sso-util admin lookup`?

**Comment by tydanielson** [comment]
I guess I'm wondering the same thing or close... my assumption was that logging in via SSO would return temporary credentials and those would be put in the credentials file.  Is this not the case?  Specifically, I'm trying to use serverless.com to perform a deploy and found your solution as an option.

**Comment by benkehoe** [comment]
When you log in via AWS SSO, which for the CLI and scripts uses the [SSO OIDC API](https://docs.aws.amazon.com/singlesignon/latest/OIDCAPIReference/Welcome.html), you end up with an OAuth token that is stored in your `~/.aws/sso/cache` directory. This single token grants access to get credentials for any of the account+roles you have access to. The actual credentials themselves are retrieved using the OAuth token through the [GetRoleCredentials](https://docs.aws.amazon.com/singlesignon/latest/PortalAPIReference/API_GetRoleCredentials.html) method of the SSO Portal API. If you're using the CLI, the CLI caches the credentials it retrieves in the `~/.aws/cli/cache` directory, so that it doesn't need to get them every time. If you're using a Python script, the credentials are not cached on disk, they are cached in memory and refreshed if they expire, because `boto3` knows how to load that OAuth token. If you're using a different language SDK, they don't have support for loading the SSO token yet, and so `aws-sso-util` provides the `aws-sso-util credential-process` mechanism, which doesn't cache the credentials, it retrieves them every time, though the SDK should cache the creds in memory and only call the credential process when the credentials expire.

That was a long-winded explanation. Does it all make sense? [The `~/.aws/credentials` file is intended for long-lived credentials](https://ben11kehoe.medium.com/aws-configuration-files-explained-9a7ea7a5b42e), in particular, IAM user keys and web tokens, not as a cache for short-lived IAM role credentials, though many tools use it that way. The AWS SDKs support mechanisms for in-memory caching and refreshing. The AWS CLI is special in that it caches credentials on disk, because there isn't a sense of "in-memory" for a shell script that uses multiple CLI commands.

**Comment by benkehoe** [comment]
Were you expecting to have to do something like `aws sso login --profile {profile-name}` every time you wanted to use a particular profile, even though you've already logged in through AWS SSO for other profiles?

**Comment by benkehoe** [comment]
hmmm...mulling over options to make `aws-sso-util lookup` more automatic...there's no way to determine using the OAuth token what account AWS SSO management happens in. You'd still have to provide an account and role name for `aws-sso-util lookup` to know what to log in to. Would it help if there were `AWS_SSO_ADMIN_ACCOUNT_ID` and `AWS_SSO_ADMIN_ROLE_NAME` environment variables you could set, and the admin parts of `aws-sso-util` would use those if you hadn't otherwise set credentials?

**Comment by ryan-mars** [comment]
Apologies for the late reply. This issue was filed based on my lack of knowledge of SSO. I didn't know what to expect from the admin commands so I ran them to learn and got a stack trace. I wasn't even aware they were "admin" commands at the time.

Receiving a stack trace instead of an error prompted me to consider this an issue. 

Now that @benkehoe has so kindly taken the time to explain the use of these commands to me (offline) I no longer consider this an issue, except that it might be nice for other newbs like me to receive a helpful error in the given case that there is nothing in `.aws/credentials`. 

@benkehoe Feel free to close this as necessary.

**Comment by benkehoe** [comment]
@ryan-mars I have added an [AWS SSO primer](https://github.com/benkehoe/aws-sso-util/blob/master/docs/primer.md) to the docs.

@tydanielson As outlined above and in the primer, the AWS credentials for a given AWS SSO role you use do not, and do not need to, end up in `~/.aws/credentials`. That being said, if you've got tools that *only look for credentials there* I have coincidentally added a `--credentials-file-profile` option to [`aws-export-credentials`](https://github.com/benkehoe/aws-export-credentials) that can help you stuff the creds generated by an AWS SSO profile into that file under another profile.
