### ISSUE TITLE
Example template for lookups

### ISSUE THREAD

**Issue by ashfaqrehman** [benkehoe/aws-sso-util#50]
@benkehoe , @oshaughnessy @OlafConijn @fai555 
Can anyone share an example macro template  or update an existing example template to showcase the usage of lookups for  `PrincipalName`, `PermissionSetName` and `TargetName` fields
https://github.com/benkehoe/aws-sso-util/blob/next/examples/template/example-template.yaml

**Comment by benkehoe** [comment]
First, it's poor etiquette to tag people when opening an issue; contributors who are interested in providing support will have subscribed to the repo to be informed of new issues.

The macro does not perform lookups for names, because it's possible for a given name to point to a different identifier at different times, and this may cause unexpected permissions to be created. [`aws-sso-util admin lookup`](https://github.com/benkehoe/aws-sso-util/blob/master/docs/lookup.md) provides a way to get the identifier based on name on the command line, and that identifier can then be put into a template.

The macro *does* look up names based on identifiers, and puts them in the metadata for a given generated `AWS::SSO::Assignment` resource. This helps give additional context when browsing the resolved template.

**Comment by ashfaqrehman** [comment]
Thanks @benkehoe and sorry for the tagging, will be careful moving forward.

The reference https://github.com/benkehoe/aws-sso-util/blob/master/docs/cloudformation.md gave me the impression it was possible instead of hard coding the ids. The !FindInMap is working as a workaround but breaks once MaxAssignmentsAllocation was set. Thanks for the clarification.
...
If you enable name lookups, the principal and permission set names will be looked up and put in the PrincipalName and PermissionSetName fields, as will the account name (in TargetName) if it wasn't generated from an OU. See below for how to enable this.
....

**Comment by benkehoe** [comment]
The header for the bulleted list you quote from is this:
> The assignment resources can contain metadata, in the Metadata section of the resource under the SSO key.

Under the "deploy macro" section:
> `LookupNames`: if set to `true`, lookup the names for identifiers on assignments and include them in the resource metadata

I have updated that list header to say:
> The assignment resources can contain the following metadata, in the `Metadata` section of the resource under the `SSO` key:
