### ISSUE TITLE
A `run-as` style command to pass creds to 3rd party tools with 'standard' CLI precedence rules.

### ISSUE THREAD

**Issue by chrismilleruk** [benkehoe/aws-sso-util#52]
I had an issue recently [discussed here](https://github.com/benkehoe/aws-sso-util/issues/24#issuecomment-1041495394) where I felt I needed to revert to a `~/.aws/credentials` file to proceed.

I looked at `aws-sso-util run-as`, and also [multiple-commands](https://github.com/benkehoe/aws-sso-util/blob/master/docs/run-as.md#multiple-commands) but the usage outlined in the docs didn't quite match my needs. 

My environment is configured in `~/.aws/config` using `aws-sso-util configure profile` but there seems no way to reference them neatly for 3rd party cli commands that perhaps don't have a full implementation (e.g. don't support `credential_process`) or follow the same precedence rules as the 'aws' cli.

From a discovery & usability perspective, it would be great to follow the `aws` cli usage & parameters:

```bash
export AWS_PROFILE=foo
aws sts get-caller-identity
aws-sso-util exec third-party-cli-tool --arg something 
aws s3 cp s3://some-bucket/some-key ./my-file
```

```bash
aws-sso-util exec --profile foo third-party-cli-tool --arg something 
```

This could either be a (breaking?) interface change to `run-as` or perhaps it's a new command `run` / `exec` / `cli` / etc.

**Comment by benkehoe** [comment]
This is not distinct from #24. `run-as` is the command-line equivalent of `aws_sso_lib.get_boto3_session()`, not of `boto3.Session()`, and not of `aws-export-credentials exec`. As I said, this is something I'm willing to be opinionated about in `aws-sso-util`.

**Comment by chrismilleruk** [comment]
> that functionality already exists and can be found in `aws-export-credentials exec` [aws-export-credentials#exec-wrapper](https://github.com/benkehoe/aws-export-credentials#exec-wrapper)

Thanks Ben, that's really helpful. I'll take a closer look at that. I had dismissed it too quickly the first time I looked.

> this is something I'm willing to be opinionated about

I definitely don't mean to offend here. As mentioned on the other thread I'm happy to respect your design decision and I'm not trying to change it in any way. 

Perhaps the differences are a little too nuanced for me to be able to understand but I am always keen to learn. What's the main reason that `aws_sso_lib.get_boto3_session()` is ok but `boto3.Session()` is not?

Thanks in advance

**Comment by benkehoe** [comment]
I wasn't taking offense; "I need the raw credentials" is a valid use case, but too often I see people reach for that answer when profiles/config would suffice. Since `aws-export-credentials` serves that use case, the "opinionated" thing I'm doing here is "don't make it too easy to fall back on handling raw credentials, help people understand when that's not actually necessary".

`aws_sso_lib.get_boto3_session()` takes as input AWS SSO configuration. It does not support referencing profiles or other kinds of credentials. `boto3.Session()` allows the full range of credential definition, of course, but you can't tell it directly to use a particular AWS SSO configuration.

`aws-sso-util run-as` is designed to support running a single command with a particular AWS SSO configuration given in the command line input (accomplished by injecting the credentials as environment variables). It's not designed to support other kinds of credentials, or access to the credentials themselves. It's explicitly not intended to bridge the "command does not support AWS SSO configuration" gap in a general way; that's what `aws-export-credentials` is for.

I have noticed that the JS SDK v2 only supports the credential process in the credentials file, not the config file; one step towards better bridging that gap is allowing `aws-sso-util configure` put the credential process in there instead/as well.

**Comment by chrismilleruk** [comment]
> I have noticed that the JS SDK v2 only supports the credential process in the credentials file, not the config file; one step towards better bridging that gap is allowing aws-sso-util configure put the credential process in there instead/as well.

That might be a good solution.

I thought the same after reading the docs. After following the source, and some testing, I found that `ProcessCredentials` *will* read the default config file if you set `AWS_SDK_LOAD_CONFIG=1` (and optionally `AWS_CONFIG_FILE`). However it quietly ignores the `filename` parameter in this mode and may have side effects for other providers. [See here](https://github.com/goldstack/goldstack/issues/17#issuecomment-1044811805)

**Comment by chrismilleruk** [comment]
> It's explicitly not intended to bridge the "command does not support AWS SSO configuration" 

I genuinely thought that was was `aws-sso-util` was for. Sorry for any misunderstanding.

Broadly, my understanding is now that tools can support SSO creds in one of the following ways (without putting them on disk or in the environment):

- direct access to the .sso cache
- using config profiles and the `sso_*` lines in config
- using profiles and `credential_process` (this is where `aws_sso_util` comes in
- using profiles and *inline* env vars (this is where `aws-export-credentials exec` can be used)

Does that sound about right?

**Comment by benkehoe** [comment]
I would categorize tools in the following way:
1. Tools that support the comprehensive set of credential options (env vars, credentials file, config for AWS SSO, role assumption, credential process). [The CLI is the reference implementation for this.](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-configure.html). `aws-sso-util` does not need to be involved.
2. Tools that support the comprehensive set *except* AWS SSO configuration. This is what `aws-sso-util` addresses with the credential process in the config. The `AWS_SDK_LOAD_CONFIG=1` thing is noted in the docs [here](https://github.com/benkehoe/aws-sso-util#adding-aws-sso-support-to-aws-sdks). Tools using the JS SDK v2 is the bulk of this category, especially since almost all the other SDKs have SSO support now.
3. Tools that only support static credentials. These are generally not using an SDK, and vary in what they support (environment only, credential file only, etc.). This is what `aws-export-credentials` is for, though it is still designed so that you should be using config profiles as input to `aws-export-credentials`.
