### ISSUE TITLE
Launch console using current AWS_PROFILE

### ISSUE THREAD

**Issue by rverma-nsl** [benkehoe/aws-sso-util#61]
Currently aws-sso-util console launch requires accountId and role. However the same info is available in saved AWS profile.
It may be a good idea to make the use of console launch without any command so that it can honour the current AWS_PROFILE.

**Comment by benkehoe** [comment]
If there are credentials available (e.g., because you're using a profile), it's no longer unique to AWS SSO (any credentials will work), so I don't really think it belongs in aws-sso-util. Good news, though: there's an issue open for that exact thing on the AWS CLI https://github.com/aws/aws-cli/issues/4642 and an associated pull request https://github.com/aws/aws-cli/pull/6365 implementing it. Head over there and slap a 👍 reaction on them 🙂
