### ISSUE TITLE
login doesn't start a browser on the Windows host when running WSL (Ubuntu-22.04)

### ISSUE THREAD

**Issue by dan-hook** [benkehoe/aws-sso-util#67]
I can launch a browser on the host from a WSL terminal using 
$ chrome https://device.sso.us-east-1.amazonaws.com/

My guess is that aws-sso-util is guessing that WSL is headless and isn't trying to launch the browser.  Is there a way to override that detection?

**Comment by dan-hook** [comment]
The host filesystem is mounted in the WSL distro and the chrome command above is an alias pointing to the chrome installation on the host.

**Comment by benkehoe** [comment]
Hm. This has always worked for me in WSL. [The code](https://github.com/benkehoe/aws-sso-util/blob/39cf9431e3ae03dc9d396ff6f4b80c5fc7889c85/lib/aws_sso_lib/browser.py#L52) uses the standard library's `webbrowser` module.

What happens if you run this in the terminal?
```
python -c "import webbrowser; webbrowser.open('https://www.python.org')"
```

Similarly, does `aws sso login` work (it uses the same mechanism)?

**Comment by dan-hook** [comment]
Thanks!  The mechanism for how the browser is launched was just the hint I needed.  I followed [this answer](https://superuser.com/a/1368878) and that solved the problem for me.  Hilariously, setting BROWSER="explorer.exe" made the python command line call work, but launched a file open dialog when used with sso login.
